export enum MODAL_TYPES {
  DRIVER = 'DRIVER',
  TRANSPORT = 'TRANSPORT',
  STATUS = 'STATUS',
  COMMENT = 'COMMENT',
  PROVISIONAL_DESTINATION = 'PROVISIONAL_DESTINATION',
  LOCATION = 'LOCATION',
}
