export enum MODAL_TYPES {
  DRIVER = 'DRIVER',
  TRANSPORT = 'TRANSPORT',
  STATUS = 'STATUS',
  COMMENT = 'COMMENT',
  PROVISIONAL_DESTINATION = 'PROVISIONAL_DESTINATION',
  LOCATION = 'LOCATION',
  RECIPIENT = 'RECIPIENT',
  SENDER = 'SENDER',
  ITEMS = 'ITEMS',
  PRIORITY = 'PRIORITY',
  ADDITION = 'ADDITION',
  COORDINATOR = 'COORDINATOR',
}
